version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/hello.babylonjs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/hello.threejs"
    schedule:
      interval: "weekly"
