version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/babylon"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/cesium"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/claygl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/react-three"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/three"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/threlte"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/trois"
    schedule:
      interval: "weekly"
